const colors = {
  light: {
    text: "#0c1a3e",
    tint: "#2563eb",
    background: "#f0f6ff",
    foreground: "#0c1a3e",
    card: "#ffffff",
    cardForeground: "#0c1a3e",
    primary: "#2563eb",
    primaryForeground: "#ffffff",
    secondary: "#dbeafe",
    secondaryForeground: "#1e3a8a",
    muted: "#e8f0fe",
    mutedForeground: "#6b7280",
    accent: "#16a34a",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#bfdbfe",
    input: "#bfdbfe",
    green: "#16a34a",
    greenForeground: "#ffffff",
  },
  dark: {
    text: "#e8f0ff",
    tint: "#3b82f6",
    background: "#070d1a",
    foreground: "#e8f0ff",
    card: "#0d1629",
    cardForeground: "#e8f0ff",
    primary: "#3b82f6",
    primaryForeground: "#ffffff",
    secondary: "#1a2744",
    secondaryForeground: "#e8f0ff",
    muted: "#1a2744",
    mutedForeground: "#7b8eb0",
    accent: "#22c55e",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#1e3057",
    input: "#1e3057",
    green: "#22c55e",
    greenForeground: "#ffffff",
  },
  radius: 12,
};

export default colors;
